Repository orbita-center/react-dadata-box, pull requests merged in 2019-12, with the labels that each got.

#24 fix: remove `/suggestions/api/4_1/rs/suggest/` path for the customEnd…
  README.md
  dist/index.js
  package-lock.json
  package.json
  src/index.js
Labels: WIP, improve

#26 V1.2.9
  README.md
  dist/index.js
  package-lock.json
  package.json
  src/index.js
Labels: RC, WIP

#27 V1.3.0
  index.d.ts
  package.json
Labels: Release

#28 bugfix of use customEndpoint as object with skipped api part
  dist/index.js
  package-lock.json
  src/index.js
Labels: bug

#29 V1.3.1
  dist/index.js
  package-lock.json
  package.json
  src/index.js
Labels: RC

#31 v1.3.2
  README.md
  dist/index.js
  examples/App.js
  examples/TestComponent.js
  index.d.ts
  package.json
  src/index.js
Labels: RC, improve

#32 Refactoring: sort object shapes, Prettier code-style
  dist/index.js
  index.d.ts
  src/index.js
Labels: refactoring
